services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - server/.env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/openpumta
      FRONTEND_URL: http://localhost:3000
      BACKEND_URL: http://localhost:4000
      PORT: 4000
    depends_on:
      - db
  db:
    ports:
      - '5450:5432'
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: openpumta
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: next-app/dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://api:4000
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://api:4000
    env_file:
      - next-app/.env
    depends_on:
      - api

volumes:
  postgres_data:
