name: Deploy on VPS
run-name: Deploying latest version
on:
  push:
    branches:
      - main
jobs:
  Deploy_ON_PUSH:
    runs-on: ubuntu-24.04
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            whoami
            docker ps
            ls
            cd openPumta/
            git pull
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml exec api pnpm prisma migrate deploy
            echo "New Changes deployed to VPS"
